#!/bin/zsh

### Get the url from a repo bundle.
#function __antidote_bundle_url {
  emulate -L zsh; setopt local_options $_adote_funcopts
  local MATCH MBEGIN MEND; local -a match mbegin mend  # appease 'warn_create_global'

  # Allow the user to define a preferred git site in case they primarily use something
  # that isn't GitHub.
  local gitsite
  zstyle -s ':antidote:gitremote' url 'gitsite' \
    || gitsite='https://github.com'
  gitsite="${gitsite%/}"

  local bundle=$1
  local url=$bundle
  if [[ $bundle != *://* && $bundle != git@*:*/* ]]; then
    url=${gitsite}/${bundle}
  fi
  print -r -- $url
#}
