#!/bin/zsh

### Get the url from a repo bundle.
#function __antidote_tourl {
  emulate -L zsh; setopt local_options $_adote_funcopts

  local bundle=$1
  local url=$bundle
  if [[ $bundle != *://* && $bundle != git@*:*/* ]]; then
    url=https://github.com/$bundle
  fi
  print $url
#}
