#!/bin/zsh
### Pretty print a path
#function __antidote_print_path {
  emulate -L zsh; setopt local_options $_adote_funcopts
  local MATCH MBEGIN MEND; local -a match mbegin mend  # appease 'warn_create_global'
  if zstyle -t ':antidote:compatibility-mode' 'antibody'; then
    print -r -- "$1"
  else
    print -r -- "${1/#$HOME/\$HOME}"
  fi
#}
