#!/bin/zsh

### Get the default cache directory per OS
#function __antidote_get_cachedir {
  emulate -L zsh; setopt $_adote_funcopts

  function __fix_windows_path {
    local path=$1
    path=${path//\\//}
    path="/${(L)path}"
    path=${path//:/}
    path=${path// /%20}
    path=${path//\%/%%}
    echo $path
  }

  local result
  if [[ "${OSTYPE}" == darwin* ]]; then
    result=$HOME/Library/Caches
  elif [[ "${OSTYPE}" == (cygwin|msys)* ]]; then
    result=$(__fix_windows_path ${LOCALAPPDATA:-$LocalAppData})
  elif [[ -n "$XDG_CACHE_HOME" ]]; then
    result=$XDG_CACHE_HOME
  else
    result=$HOME/.cache
  fi

  if [[ -n "$1" ]]; then
    if [[ $result == *\\* ]]; then
      result+="\\$1"
    else
      result+="/$1"
    fi
  fi
  print -r -- $result
#}
