#!/bin/zsh

### Get the short repo name of the bundle.
#function __antidote_bundle_repo {
  emulate -L zsh; setopt local_options $_adote_funcopts
  local bundle=$1
  local bundle_type="$(__antidote_bundle_type $bundle)"
  if [[ "$bundle_type" == (url|sshurl) ]]; then
    bundle=${bundle%.git}
    bundle=${bundle:gs/\:/\/}
    local parts=(${(ps./.)bundle})
    print -r -- ${parts[-2]}/${parts[-1]}
  elif [[ "$bundle_type" == repo ]]; then
    print -r -- $bundle
  else
    return 1
  fi
#}
