#!/bin/zsh

### Get the short name of the bundle.
#function __antidote_bundle_name {
  emulate -L zsh; setopt local_options $_adote_funcopts
  local bundle=$1
  local bundle_type="$(__antidote_bundle_type $bundle)"
  if [[ "$bundle_type" == (url|sshurl) ]] ; then
    bundle=${bundle%.git}
    bundle=${bundle:gs/\:/\/}
    local parts=(${(ps./.)bundle})
    print ${parts[-2]}/${parts[-1]}
  else
    __antidote_scrub_home "$bundle"
  fi
#}
