#!/bin/zsh

### For compatibility with antidote versions <= 1.8.8
### TODO: remove sometime after 2023-09-30: https://github.com/mattmc3/antidote/issues/139
### Setup antidote.
#function __antidote_core {
typeset -f __antidote_setup &>/dev/null && unfunction __antidote_setup
0=${(%):-%x}
autoload -Uz ${0:A:h}/__antidote_setup
__antidote_setup
#}
