#!/bin/zsh

### Get the name of the bundle.
#function __antidote_bundle_name {
  emulate -L zsh; setopt local_options $_adote_funcopts
  local bundle repo
  bundle="$1"
  repo="$(__antidote_bundle_repo $bundle)"
  if [[ -n "$repo" ]]; then
    print -r -- "$repo"
  else
    __antidote_scrub_home "$bundle"
  fi
#}
