#!/usr/bin/env zsh

local bundlestr parts bundle optstr opts
typeset -A opts

for bundlestr in $@; do
  parts=(${(@s/ /)bundlestr})
  bundle=$parts[1]
  optstr=(${parts[@]:1})
  opts=(${(@s/:/)optstr})
  if [[ $bundle = \$* ]] || [[ $bundle = /* ]]; then
    # path bundles
    continue
  elif [[ $bundle = */* ]]; then
    # repos
    _antidote_clone $bundle ${opts[branch]}
  fi
done
