#!/bin/zsh

local bundle="$1"
if zstyle -t ':antidote:bundle' use-friendly-name; then
  echo $(antidote-home)/${${bundle:t}%.git}
else
  # sanitize URL for safe use as a dir name
  local url=$(_antidote_tourl $bundle)
  url=${url:gs/\@/-AT-}
  url=${url:gs/\:/-COLON-}
  url=${url:gs/\//-SLASH-}
  echo $(antidote-home)/$url
fi
