#!/bin/zsh

local pluginstr parts plugin optstr opts
typeset -A opts

for pluginstr in $@; do
  parts=(${(@s/ /)pluginstr})
  plugin=$parts[1]
  optstr=(${parts[@]:1})
  opts=(${(@s/:/)optstr})
  if [[ $plugin = \$* ]] || [[ $plugin = /* ]]; then
    # path plugins
    continue
  elif [[ $plugin = */* ]]; then
    # repos
    _antidote_clone $plugin ${opts[branch]}
  fi
done
