#!/usr/bin/env zsh

local bundle="$1"

if [[ -d "$bundle" ]]; then
  echo $bundle
elif zstyle -t ':antidote:bundle' use-friendly-names; then
  # zsh-users/zsh-autosuggestions becomes zsh-users__zsh-autosuggestions
  bundle=${bundle%.git}
  bundle=${bundle:gs/\:/\/}
  local parts=(${(@s:/:)bundle})
  if [[ $#parts -gt 1 ]]; then
    echo $(antidote-home)/${parts[-2]}__${parts[-1]}
  else
    echo $(antidote-home)/$bundle
  fi
else
  # sanitize URL for safe use as a dir name
  local url=$(_antidote_tourl $bundle)
  url=${url:gs/\@/-AT-}
  url=${url:gs/\:/-COLON-}
  url=${url:gs/\//-SLASH-}
  echo $(antidote-home)/$url
fi
