#!/usr/bin/env zsh

local bundle="$1"

if [[ -d "$bundle" ]]; then
  echo $bundle
elif zstyle -t ':antidote:bundle' use-friendly-names; then
  echo $(_antidote_friendlyname "$bundle")
else
  # sanitize URL for safe use as a dir name
  local url=$(_antidote_tourl $bundle)
  url=${url:gs/\@/-AT-}
  url=${url:gs/\:/-COLON-}
  url=${url:gs/\//-SLASH-}
  echo $(antidote-home)/$url
fi
