#!/usr/bin/env zsh

### Get a friendly path for a bundle dir.

# $ANTIDOTE_HOME/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-autosuggestions
# becomes simply
# $ANTIDOTE_HOME/zsh-users/zsh-autosuggestions

repo=$1
bundle=${repo%.git}
bundle=${bundle:gs/\:/\/}
local parts=(${(@s:/:)bundle})
if [[ $#parts -gt 1 ]]; then
  echo $(antidote-home)/${parts[-2]}/${parts[-1]}
else
  echo $(antidote-home)/$bundle
fi
