#!/usr/bin/env zsh

### Clone a git repo containing a Zsh plugin.

emulate -L zsh
setopt local_options extended_glob

local flag_bg=false
if [[ "$1" == "--background" ]]; then
  flag_bg=true
  shift
fi

local bundle=$1
local branch=$2
local giturl=$(_antidote_tourl $bundle)
local bundledir=$(_antidote_bundledir $giturl)

if [[ ! -d $bundledir ]]; then
  [[ -z "$branch" ]] || branch="--branch=$branch"
  echo >&2 "# antidote cloning $bundle..."
  if [[ "$flag_bg" == true ]]; then
    _antidote_git clone --quiet --depth 1 --recurse-submodules --shallow-submodules $branch $giturl $bundledir &
  else
    _antidote_git clone --quiet --depth 1 --recurse-submodules --shallow-submodules $branch $giturl $bundledir
  fi
fi
