#!/bin/zsh
local bundle=$1
local kind=$2

[[ $kind != clone ]] || return

local bundledir=$(_antidote_bundledir $bundle)

if [[ $kind = fpath ]]; then
  echo "fpath+=( $bundledir )"
elif [[ $kind = path ]]; then
  echo "export PATH=\"$bundledir:\$PATH\""
else
  echo "fpath+=( $bundledir )"
  local initfile REPLY
  _antidote_initfile $bundle >/dev/null || return 1
  initfile=$REPLY
  if [[ $kind = defer ]]; then
    echo "zsh-defer source $initfile"
  else
    echo "source $initfile"
  fi
fi
