#!/bin/zsh

### antidote - the cure to slow zsh plugin management
#
# https://getantidote.github.io
# run `antidote -h` for usage
#
# Note: this gets overridden if using `antidote init`.
#
#function antidote {
  0=${(%):-%x}
  (( $+functions[antidote-main] )) || source ${0:A:h:h}/antidote.zsh
  antidote-main "$@"
#}
