#!/usr/bin/env zsh

### Alias for `antidote bundle` to support legacy syntax.
###
### usage: antidote bundles [-h|--help] <bundle>...

local opts
zparseopts -A opts -D -F -- h -help || return 1

if [[ -v opts[-h] ]] || [[ -v opts[--help] ]]; then
  antidote-help bundles
  return
fi

antidote-bundle "$@"
