#!/usr/bin/env zsh

### Alias for `antidote bundle` to support legacy syntax.
###
### usage: antidote bundles [-h|--help] <bundle>...

local o_help
zparseopts -D -F -K -- \
  {h,-help}=o_help ||
  return 1

if (( $#o_help )); then
  antidote-help bundles
  return
fi

antidote-bundle "$@"
