#!/usr/bin/env zsh

### Update antidote.
###
### usage: antidote selfupdate [-h|--help]

emulate -L zsh
setopt local_options extended_glob
0=${(%):-%x}

local opts
zparseopts -A opts -D -F -- h -help || return 1

if [[ -v opts[-h] ]] || [[ -v opts[--help] ]]; then
  antidote-help selfupdate
  return
fi

# update antidote
echo "Updating antidote..."
git -C "${0:A:h:h}" pull --ff --rebase --autostash
