#!/usr/bin/env zsh

### Print the path of a cloned bundle.
###
### usage: antidote path [-h|--help] <bundle>

emulate -L zsh
setopt local_options extended_glob

local opts
zparseopts -A opts -D -F -- h -help || return 1

if [[ -v opts[-h] ]] || [[ -v opts[--help] ]]; then
  antidote-help path
  return
fi

if [[ $# -eq 0 ]]; then
  echo >&2 "antidote: error: required argument 'bundle' not provided, try --help"
  return 1
fi

local bundle="$1"
local bundledir=$(_antidote_bundledir $bundle)
if [[ ! -d $bundledir ]]; then
  echo >&2 "antidote: error: $bundle does not exist in cloned paths"
  return 1
else
  echo "$bundledir"
fi
