#!/usr/bin/env zsh
if ! (( $+functions[antidote-help] )); then
  0=${(%):-%x}
  for _fn in ${0:A:h}/*; do
    (( $+functions[${_fn:t}] )) || autoload -Uz $_fn
  done
  unset _fn
fi

local cmd="$1"

if (( $+functions[antidote-${cmd}] )); then
  shift
  antidote-${cmd} "$@"
  return $?
elif [[ -z "$cmd" ]] || [[ $cmd = (--help|-h) ]]; then
  antidote-help
else
  echo >&2 "antidote: command not found '${cmd}'" && return 1
fi
