#!/usr/bin/env zsh

##? usage: antidote [<flags>] <command> [<args> ...]
##?
##? the cure to slow zsh plugin management
##?
##? Flags:
##?   -h, --help           Show context-sensitive help
##?   -v, --version        Show application version
##?
##? Commands:
##?   help [<command>...]
##?     Show help
##?
##?   bundle [<bundles>...]
##?     Downloads a bundle and prints its source line
##?
##?   update
##?     Updates all previously bundled bundles
##?
##?   home
##?     Prints where antidote is cloning the bundles
##?
##?   purge <bundle>
##?     Purges a bundle from your computer
##?
##?   list
##?     Lists all currently installed bundles
##?
##?   path <bundle>
##?     Prints the path of a currently cloned bundle
##?
##?   init
##?     Initializes the shell so antidote can behave like legacy antibody/antigen
##?
##?   install
##?     Add a new bundle to your plugins file
##?
##?   load
##?     Source all bundles in your plugins file

# Note that this function gets overridden if using `antidote-init`.

if ! (( $+functions[_antidote_main] )); then
  0=${(%):-%x}
  autoload -Uz ${0:h}/_antidote_main
fi
_antidote_main "$@"
