#!/usr/bin/env zsh

local script=(
  '#!/usr/bin/env zsh'
  'function antidote {'
  '  case "$1" in'
  '    bundle)'
  '      source <( _antidote_main $@ ) || _antidote_main $@'
  '      ;;'
  '    *)'
  '      _antidote_main $@'
  '      ;;'
  '  esac'
  '}'
)
printf "%s\n" "${script[@]}"
