#!/bin/zsh

#function antidote2 {
  emulate -L zsh; setopt local_options $_adote_funcopts

  ANTIDOTE_HOME="$ANTIDOTE_HOME" \
    XDG_CACHE_HOME="$XDG_CACHE_HOME" \
    LOCALAPPDATA="${LOCALAPPDATA:-$LocalAppData}" \
    ANTIDOTE_OSTYPE="${ANTIDOTE_OSTYPE:-$OSTYPE}" \
    ANTIDOTE_GITCMD="${ANTIDOTE_GITCMD:-git}" \
    zsh "$__ANTIDOTE2_ZSH" "$@"
#}
