#!/bin/zsh

### Run antidote.zsh in a subprocess.
#function antidote-zsh {
  emulate -L zsh; setopt local_options

  ANTIDOTE_ZSTYLES="$(zstyle -L ':antidote:*')" \
  ANTIDOTE_HOME="${ANTIDOTE_HOME}" \
  ANTIDOTE_TMPDIR="${TMPDIR}" \
  zsh "$ANTIDOTE_ZSH" "$@"
#}
