#!/usr/bin/env zsh

# There's a chicken-and-egg problem here in that we are using an untested antidote to
# generate the desired output for tests. The reason this is okay is simply this: git.
# Since we store the resulting file in git, can diff it and do manual verification that
# the output really is correct. This is for convenience only.

0=${(%):-%x}

export ANTIDOTE_HOME=$(mktemp -d -t antidote-regen)
echo "ANTIDOTE_HOME=$ANTIDOTE_HOME"

prj_dir=${0:a:h:h:h}
source $prj_dir/antidote.zsh

# set the output files
txtfile=${0:h}/real_plugins.txt
zshfile=${0:h}/real_plugins.zsh
listfile=${0:h}/real_clonelist.txt

# drink the antidote
antidote bundle <$txtfile >$zshfile
antidote list >$listfile

# use variables instead of absolute path
sed -i '' "s|$ANTIDOTE_HOME|\$ANTIDOTE_HOME|g" $zshfile
sed -i '' "s|/private${ANTIDOTE_HOME}|\$ANTIDOTE_HOME|g" $listfile
sed -i '' "s|$ANTIDOTE_HOME|\$ANTIDOTE_HOME|g" $listfile

# cleanup
if [[ -d "$ANTIDOTE_HOME" ]] && [[ "$ANTIDOTE_HOME" = *antidote-regen* ]]; then
  rm -rf "$ANTIDOTE_HOME"
fi
