#!/usr/bin/env zsh
# @echo "fakegit clone $@"

local giturl=${@[-2]}
local bundledir=${@[-1]}
local reponame=${${giturl%.git}:t}

if [[ ! -d "$TEST_HOME/fakerepos/$reponame" ]]; then
  echo >&2 "Fake repo not found '$reponame'."
  return 1
elif [[ -d "$bundledir" ]]; then
  echo >&2 "Fake repo already fake cloned '$giturl'."
  return 1
fi

cp -a "$TEST_HOME/fakerepos/$reponame" "$bundledir"
