#!/bin/zsh
#function print_aarr() {
  # Generic matrix printer. Reads 'typeset -p' output from stdin via eval,
  # then prints all key-value pairs for the given matrix variable and count variable.
  # usage: some_serializer | print_aarr <matrix_var> <count_var>
  #
  emulate -L zsh; setopt local_options

  local matrix_var=${1:-_parsed_bundles} count_var=${2:-_parsed_bundles_count}
  local -a all_keys row_keys
  local i key val

  eval "$(cat)"
  all_keys=(${(ok)${(P)matrix_var}})
  for (( i = 1; i <= ${(P)count_var}; i++ )); do
    row_keys=()
    for key in $all_keys; do
      [[ $key == $i,* ]] && row_keys+=(${key#$i,})
    done
    for key in ${(o)row_keys}; do
      val="$(print -r -- "${${(P)matrix_var}[$i,$key]}" | subenv ANTIDOTE_HOME)"
      if [[ -z "$val" ]]; then
        printf '%-12s:\n' $key
      else
        printf '%-12s: %s\n' $key $val
      fi
    done
  done
#}
