#!/bin/zsh
#function print_aarr() {
  emulate -L zsh; setopt local_options

  local input key val
  local -A bundle

  while IFS= read -r input; do
    [[ -z "$input" ]] && continue
    bundle=("${(@Q)${(z)input}}")
    for key in ${(ok)bundle}; do
      [[ "$key" == __lineno__ ]] && continue
      val="$( print -r -- "${bundle[$key]}" | subenv ANTIDOTE_HOME )"
      if [[ -z "$val" ]]; then
        printf '%-12s:\n' $key
      else
        printf '%-12s: %s\n' $key $val
      fi
    done
  done
#}
