#!/bin/zsh

ZDOTDIR=$BASEDIR/.tmp/tests/${1:-tmp}
ANTIDOTE_HOME=$ZDOTDIR/antidote
[[ -d $ANTIDOTE_HOME ]] && rm -rf $ANTIDOTE_HOME

# create a fake plugin
local bundledir="$ANTIDOTE_HOME/https-COLON--SLASH--SLASH-github.com-SLASH-foo-SLASH-bar"
mkdir -p $bundledir
typeset -g REPLY=$bundledir/bar.zsh
touch $REPLY
echo $REPLY
