#!/bin/zsh
function setup_fakezdotdir {
  # setup zsh home
  local name=${1:-temp}
  typeset -g ZSHDIR=$BASEDIR/.tmp/tests/$name
  [[ -d $ZSHDIR ]] && rm -rf $ZSHDIR
  mkdir -p ${ZSHDIR:h}
  cp -rf "$FAKEZDOTDIR" "$ZSHDIR"

  # setup antidote home
  typeset -g ANTIDOTE_HOME=$ZSHDIR/antidote_home
  local _d
  for _d in $ANTIDOTE_HOME/*(/N); do
    [[ -d "$_d/.mockgit" ]] || mkdir -p "$_d/.mockgit"
  done

  # switch ZDOTDIR
  typeset -g OLD_ZDOTDIR=$ZDOTDIR
  typeset -g ZDOTDIR=$ZSHDIR
}
setup_fakezdotdir "$@"
