#!/usr/bin/env zsh

0=${(%):-%x}
for _fn in ${0:A:h}/*; do
  (( $+functions[${_fn:t}] )) || autoload -Uz $_fn
done
unset _fn

PRJ_HOME=${0:a:h:h:h}
TEST_HOME=${0:a:h:h}
export ANTIDOTE_HOME=$(mktemp -d -t ztap)
@echo "temp ANTIDOTE_HOME=$ANTIDOTE_HOME"
