#!/usr/bin/env zsh

0=${(%):-%x}
local user_repo=$1; shift
local user=${user_repo%/*}
local repo=${user_repo#*/}

ZDOTDIR=$TEMP_HOME
echo $user_repo >>$ZDOTDIR/.zsh_plugins.txt
local plugin_dir="${ANTIDOTE_HOME}/https-COLON--SLASH--SLASH-github.com-SLASH-${user}-SLASH-${repo}"
mkdir -p $plugin_dir
local plugin_file="${plugin_dir}/${repo}.plugin.zsh"
printf "%s\n" "${(@)@}" >$plugin_file
