#!/usr/bin/env zsh
0=${(%):-%x}
BASEDIR=${0:A:h:h:h}

# initialize test functions
local func
for func in ${0:A:h}/*; do
  (( $+functions[${func:t}] )) || autoload -Uz $func
done
unset func

source $BASEDIR/tests/ztap/ztap3.zsh
