#!/bin/zsh

function testinit {
  0=${(%):-%x}
  typeset -g BASEDIR=${0:A:h:h:h}
  typeset -g TMPDIR=$BASEDIR/.tmp
  typeset -g ZTAP_HOME=${ZTAP_HOME:-$TMPDIR/ztap}
  typeset -g TESTDIR=$BASEDIR/tests
  typeset -g FAKEZDOTDIR=$BASEDIR/tests/zdotdir
  typeset -g REALZDOTDIR=$BASEDIR/tests/realzdotdir
  setopt warn_create_global warn_nested_var

  zstyle ':antidote:tests' set-warn-options 'on'

  # initialize test functions
  local func
  for func in ${0:A:h}/*; do
    (( $+functions[${func:t}] )) || autoload -Uz $func
  done
  unset func

  source $ZTAP_HOME/ztap3.zsh
}
testinit "$@"
