#!/usr/bin/env zsh
# Bench setup for zinit.
#
# OMZ files come from snippets rather than a full clone.
emulate -L zsh
setopt err_return

: ${BENCH_HOME:?not set}

if [[ ! -f $BENCH_HOME/.zinit/zinit.git/zinit.zsh ]]; then
  rm -rf $BENCH_HOME/.zinit/zinit.git
  git clone --quiet --depth 1 https://github.com/zdharma-continuum/zinit.git \
    $BENCH_HOME/.zinit/zinit.git
fi

cp -r -- ${0:A:h}/skel/*(D) $BENCH_HOME/
