'\" t
.\"     Title: antidote-bundle
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.26
.\"      Date: 2025-12-12
.\"    Manual: Antidote Manual
.\"    Source: antidote
.\"  Language: English
.\"
.TH "ANTIDOTE\-BUNDLE" "1" "2025-12-12" "antidote" "Antidote Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
antidote-bundle \- download a bundle and print its source line
.SH "SYNOPSIS"
.sp
\fBantidote bundle\fP [<bundles>.\|.\|.]
.SH "DESCRIPTION"
.sp
\fBantidote\-bundle\fP assembles your Zsh plugins. Bundles can be git repos, or local files or directories. If a plugin is a repo, it will be cloned if necessary. The zsh code necessary to load (source) the plugin is then printed.
.sp
.if n .RS 4
.nf
.fam C
antidote bundle gituser/gitrepo
antidote bundle $ZSH_CUSTOM/plugins/myplugin
antidote bundle ${ZDOTDIR:\-$HOME}/.zlibs/myfile.zsh
.fam
.fi
.if n .RE
.sp
Bundles also support annotations. Annotations allow you have finer grained control over your plugins. Annotations are used in the form \f(CRkeyword:value\fP.
.sp
\f(CRkind\fP
.RS 4
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\fBzsh\fP: A zsh plugin. This is the default kind of bundle.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\fBfpath\fP: Only add the plugin to your \f(CR$fpath\fP.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\fBpath\fP: Add the plugin to your \f(CR$PATH\fP.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\fBclone\fP: Only clone a plugin, but don\(cqt do anything else with it.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\fBdefer\fP: Defers loading of a plugin using \f(CRromkatv/zsh\-defer\fP.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\fBautoload\fP: Autoload all the files in the plugin directory as zsh functions.
.RE
.RE
.sp
\f(CRbranch\fP
.RS 4
The branch annotation allows you to change the default branch of a plugin\(cqs repo from \fBmain\fP to a branch of your choosing.
.RE
.sp
\f(CRpath\fP
.RS 4
The path annotation allows you to use a subdirectory or file within a plugin\(cqs structure instead of the root plugin (eg: \f(CRpath:plugins/subplugin\fP).
.RE
.sp
\f(CRconditional\fP
.RS 4
The conditional annotation allows you to wrap an \fBif\fP statement around a plugin\(cqs load script. Supply the name of a zero argument zsh function to conditional to perform the test (eg: \f(CRconditional:is\-macos\fP).
.RE
.sp
\f(CRpre\fP / \f(CRpost\fP
.RS 4
The pre and post annotations allow you to call a function before or after a plugin\(cqs load script. This is helpful when configuring plugins, since the configuration functions will only run for active plugins. Supply the name of a zero argument zsh function to pre or post.
.RE
.sp
\f(CRautoload\fP
.RS 4
The autoload annotation allows you to autoload a zsh functions directory in addition to however the plugin was loaded as specified by \f(CRkind\fP. Supply a relative path to autoload (eg: \f(CRautoload:functions\fP).
.RE
.sp
Cloned repo directory names can be overridden with the following \f(CRzstyle\fP:
.sp
.if n .RS 4
.nf
.fam C
zstyle \*(Aq:antidote:bundle\*(Aq use\-friendly\-names \*(Aqyes\*(Aq
.fam
.fi
.if n .RE
.SH "OPTIONS"
.sp
\fB\-h, \-\-help\fP
.RS 4
Show the help documentation.
.RE
.sp
\fB<bundles>.\|.\|.\fP
.RS 4
Zsh plugin bundles.
.RE
.SH "EXAMPLES"
.sp
Using the \fBkind:\fP annotation:
.sp
.if n .RS 4
.nf
.fam C
# a regular plugin (kind:zsh is implied, so it\*(Aqs unnecessary)
antidote bundle zsh\-users/zsh\-history\-substring\-search kind:zsh
.fam
.fi
.if n .RE
.sp
.if n .RS 4
.nf
.fam C
# add prompt plugins to $fpath
antidote bundle sindresorhus/pure kind:fpath
.fam
.fi
.if n .RE
.sp
.if n .RS 4
.nf
.fam C
# add utility plugins to $PATH
antidote bundle romkatv/zsh\-bench kind:path
.fam
.fi
.if n .RE
.sp
.if n .RS 4
.nf
.fam C
# clone a repo for use in other ways
antidote bundle mbadolato/iTerm2\-Color\-Schemes kind:clone
.fam
.fi
.if n .RE
.sp
.if n .RS 4
.nf
.fam C
# autoload a functions directory
antidote bundle sorin\-ionescu/prezto path:modules/utility/functions kind:autoload
.fam
.fi
.if n .RE
.sp
.if n .RS 4
.nf
.fam C
# defer a plugin to speed up load times
antidote bundle olets/zsh\-abbr kind:defer
.fam
.fi
.if n .RE
.sp
Using the \fBbranch:\fP annotation:
.sp
.if n .RS 4
.nf
.fam C
# don\*(Aqt use the main branch, use develop instead
antidote bundle zsh\-users/zsh\-autosuggestions branch:develop
.fam
.fi
.if n .RE
.sp
Using the \fBpath:\fP annotation:
.sp
.if n .RS 4
.nf
.fam C
# load oh\-my\-zsh
antidote bundle ohmyzsh/ohmyzsh path:lib
antidote bundle ohmyzsh/ohmyzsh path:plugins/git
.fam
.fi
.if n .RE
.sp
Using the \fBconditional:\fP annotation:
.sp
.if n .RS 4
.nf
.fam C
# define a conditional function prior to loading antidote
function is_macos {
  [[ $OSTYPE == darwin* ]] || return 1
}

# conditionally load a plugin using the function you made
antidote bundle ohmyzsh/ohmyzsh path:plugins/macos conditional:is_macos
.fam
.fi
.if n .RE
.SH "BUGS"
.sp
See GitHub Issues: \c
.URL "https://github.com/mattmc3/antidote/issues" "" ""
.SH "AUTHORS"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Copyright (c) 2021\-2026 Matt McElheny
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
antidote contributors: \c
.URL "https://github.com/mattmc3/antidote/graphs/contributors" "" ""
.RE
.SH "LICENSE"
.sp
MIT