'\" t
.\"     Title: antidote-path
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.26
.\"      Date: 2025-12-12
.\"    Manual: Antidote Manual
.\"    Source: antidote
.\"  Language: English
.\"
.TH "ANTIDOTE\-PATH" "1" "2025-12-12" "antidote" "Antidote Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
antidote-path \- print the path of a cloned bundle
.SH "SYNOPSIS"
.sp
\fBantidote path\fP <bundle>
.SH "DESCRIPTION"
.sp
\fBantidote\-path\fP prints the path of a cloned bundle.
.SH "OPTIONS"
.sp
\fB\-h, \-\-help\fP
.RS 4
Show the help documentation.
.RE
.sp
\fB[<bundle>]\fP
.RS 4
The bundle whose cloned path will be printed.
.RE
.SH "BUGS"
.sp
See GitHub Issues: \c
.URL "https://github.com/mattmc3/antidote/issues" "" ""
.SH "AUTHORS"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Copyright (c) 2021\-2026 Matt McElheny
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
antidote contributors: \c
.URL "https://github.com/mattmc3/antidote/graphs/contributors" "" ""
.RE
.SH "LICENSE"
.sp
MIT