'\" t
.\"     Title: antidote-home
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.26
.\"      Date: 2025-12-12
.\"    Manual: Antidote Manual
.\"    Source: antidote
.\"  Language: English
.\"
.TH "ANTIDOTE\-HOME" "1" "2025-12-12" "antidote" "Antidote Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
antidote-home \- print where antidote is cloning bundles
.SH "SYNOPSIS"
.sp
\fBantidote home\fP
.SH "DESCRIPTION"
.sp
\fBantidote\-home\fP shows you where antidote stores its cloned repos. It is not the home of the antidote utility itself.
.sp
.if n .RS 4
.nf
.fam C
antidote home
.fam
.fi
.if n .RE
.sp
You can override antidote\(cqs default home directory by setting the \f(CR$ANTIDOTE_HOME\fP variable in your \f(CR.zshrc\fP.
.SH "OPTIONS"
.sp
\fB\-h, \-\-help\fP
.RS 4
Show the help documentation.
.RE
.SH "EXAMPLES"
.sp
You can clear out all your cloned repos like so:
.sp
.if n .RS 4
.nf
.fam C
rm \-rfi "$(antidote home)"
.fam
.fi
.if n .RE
.SH "BUGS"
.sp
See GitHub Issues: \c
.URL "https://github.com/mattmc3/antidote/issues" "" ""
.SH "AUTHORS"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Copyright (c) 2021\-2026 Matt McElheny
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
antidote contributors: \c
.URL "https://github.com/mattmc3/antidote/graphs/contributors" "" ""
.RE
.SH "LICENSE"
.sp
MIT