'\" t
.\"     Title: antidote-snapshot
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.26
.\"      Date: 2026-04-02
.\"    Manual: Antidote Manual
.\"    Source: antidote
.\"  Language: English
.\"
.TH "ANTIDOTE\-SNAPSHOT" "1" "2026-04-02" "antidote" "Antidote Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
antidote-snapshot \- save, restore, remove, or list bundle snapshots
.SH "SYNOPSIS"
.sp
\fBantidote snapshot\fP home
.sp
\fBantidote snapshot\fP list
.sp
\fBantidote snapshot\fP remove [<file>.\|.\|.]
.sp
\fBantidote snapshot\fP restore [<file>]
.sp
\fBantidote snapshot\fP save [<file>]
.SH "DESCRIPTION"
.sp
\fBantidote\-snapshot\fP manages point\-in\-time snapshots of your cloned bundles. A snapshot is a bundle file where every repository is annotated with \f(CRkind:clone pin:<SHA>\fP, capturing the exact commit of each cloned bundle.
.sp
Snapshots are saved automatically during \f(CRantidote update\fP in static mode. They are not created in dynamic mode.
.sp
By default, snapshots are stored in \f(CR$XDG_DATA_HOME/antidote/snapshots\fP (or \f(CR~/Library/Application Support/antidote/snapshots\fP on macOS). A rolling history is maintained, with older snapshots pruned beyond the configured maximum.
.SH "SUBCOMMANDS"
.sp
\fBhome\fP
.RS 4
Print the path to the snapshot directory.
.RE
.sp
\fBlist\fP
.RS 4
List all available snapshot files.
.RE
.sp
\fBremove\fP
.RS 4
Remove snapshot files. If no file is given and \f(CRfzf\fP is available, an interactive multi\-select picker is shown.
.RE
.sp
\fBrestore\fP
.RS 4
Restore bundles from a snapshot file. If no file is given, the most recent snapshot is used.
.RE
.sp
\fBsave\fP
.RS 4
Save a snapshot of all currently cloned bundles. Optionally specify a file path; otherwise a timestamped file is created in the snapshot directory.
.RE
.SH "OPTIONS"
.sp
\fB\-h, \-\-help\fP
.RS 4
Show the help documentation.
.RE
.SH "CONFIGURATION"
.sp
The snapshot directory can be customized:
.sp
.if n .RS 4
.nf
.fam C
zstyle \*(Aq:antidote:snapshot\*(Aq dir ~/.antidote\-snapshots
.fam
.fi
.if n .RE
.sp
The maximum number of snapshots to keep (default 100):
.sp
.if n .RS 4
.nf
.fam C
zstyle \*(Aq:antidote:snapshot\*(Aq max 25
.fam
.fi
.if n .RE
.sp
The command used for interactive snapshot selection (default \f(CRfzf\fP).
Set it to an empty value to disable picker\-based selection:
.sp
.if n .RS 4
.nf
.fam C
zstyle \*(Aq:antidote:fzf\*(Aq cmd fzf
zstyle \*(Aq:antidote:fzf\*(Aq cmd \*(Aq\*(Aq
.fam
.fi
.if n .RE
.sp
Set the \f(CRFZF_DEFAULT_OPTS\fP and \f(CRFZF_DEFAULT_OPTS_FILE\fP used for fzf in antidote:
.sp
.if n .RS 4
.nf
.fam C
zstyle \*(Aq:antidote:fzf\*(Aq opts "\-\-height=40% \-\-layout=reverse"
zstyle \*(Aq:antidote:fzf\*(Aq opts_file ~/.config/antidote/fzf\-opts
.fam
.fi
.if n .RE
.sp
If \f(CRbat\fP is installed, it is used for syntax\-highlighted fzf previews. If the Antidote Bundle syntax definition is also installed, it will be used; otherwise bat falls back to \f(CRproperties\fP syntax. Set bat options with the following zstyle:
.sp
.if n .RS 4
.nf
.fam C
zstyle \*(Aq:antidote:bat\*(Aq opts "\-\-style=plain"
.fam
.fi
.if n .RE
.sp
Disable auto\-snapshots on \f(CRantidote update\fP (explicit \f(CRantidote snapshot save\fP still works):
.sp
.if n .RS 4
.nf
.fam C
zstyle \*(Aq:antidote:snapshot:automatic\*(Aq enabled no
.fam
.fi
.if n .RE
.SH "EXAMPLES"
.sp
Show where snapshots are stored:
.sp
.if n .RS 4
.nf
.fam C
antidote snapshot home
.fam
.fi
.if n .RE
.sp
Save a snapshot:
.sp
.if n .RS 4
.nf
.fam C
antidote snapshot save
.fam
.fi
.if n .RE
.sp
List snapshots:
.sp
.if n .RS 4
.nf
.fam C
antidote snapshot list
.fam
.fi
.if n .RE
.sp
Restore from the most recent snapshot:
.sp
.if n .RS 4
.nf
.fam C
antidote snapshot restore
.fam
.fi
.if n .RE
.sp
Restore from a specific snapshot:
.sp
.if n .RS 4
.nf
.fam C
antidote snapshot restore ~/.local/share/antidote/snapshots/snapshot\-20260101\-120000.txt
.fam
.fi
.if n .RE
.SH "BUGS"
.sp
See GitHub Issues: \c
.URL "https://github.com/mattmc3/antidote/issues" "" ""
.SH "AUTHORS"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Copyright (c) 2021\-2026 Matt McElheny
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
antidote contributors: \c
.URL "https://github.com/mattmc3/antidote/graphs/contributors" "" ""
.RE
.SH "LICENSE"
.sp
MIT