'\" t
.\"     Title: antidote-bundle
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.26
.\"      Date: 2026-08-06
.\"    Manual: Antidote Manual
.\"    Source: antidote
.\"  Language: English
.\"
.TH "ANTIDOTE\-BUNDLE" "1" "2026-08-06" "antidote" "Antidote Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
antidote-bundle \- download a bundle and print its source line
.SH "SYNOPSIS"
.sp
\fBantidote bundle\fP [<bundles>.\|.\|.]
.SH "DESCRIPTION"
.sp
\fBantidote\-bundle\fP assembles your Zsh plugins. Bundles can be git repos, or local files or directories. If a plugin is a repo, it will be cloned if necessary. The zsh code necessary to load (source) the plugin is then printed.
.sp
.if n .RS 4
.nf
.fam C
antidote bundle gituser/gitrepo
antidote bundle $ZSH_CUSTOM/plugins/myplugin
antidote bundle ${ZDOTDIR:\-$HOME}/.zlibs/myfile.zsh
.fam
.fi
.if n .RE
.sp
Bundles also support annotations. Annotations allow you have finer grained control over your plugins. Annotations are used in the form \f(CRkeyword:value\fP.
.sp
\f(CRkind\fP
.RS 4
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\fBzsh\fP: A zsh plugin. This is the default kind of bundle.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\fBfpath\fP: Only add the plugin to your \f(CR$fpath\fP.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\fBpath\fP: Add the plugin to your \f(CR$PATH\fP.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\fBclone\fP: Only clone a plugin, but don\(cqt do anything else with it.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\fBdefer\fP: Defers loading of a plugin using \f(CRromkatv/zsh\-defer\fP.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\fBautoload\fP: Autoload all the files in the plugin directory as zsh functions.
.RE
.RE
.sp
\f(CRbranch\fP
.RS 4
The branch annotation allows you to change the default branch of a plugin\(cqs repo from \fBmain\fP to a branch of your choosing.
.RE
.sp
\f(CRpath\fP
.RS 4
The path annotation allows you to use a subdirectory or file within a plugin\(cqs structure instead of the root plugin (eg: \f(CRpath:plugins/subplugin\fP).
.RE
.sp
\f(CRconditional\fP
.RS 4
The conditional annotation allows you to wrap an \fBif\fP statement around a plugin\(cqs load script. Supply the name of a zero argument zsh function to conditional to perform the test (eg: \f(CRconditional:is\-macos\fP).
.RE
.sp
\f(CRpre\fP / \f(CRpost\fP
.RS 4
The pre and post annotations allow you to call a function before or after a plugin\(cqs load script. This is helpful when configuring plugins, since the configuration functions will only run for active plugins. Supply the name of a zero argument zsh function to pre or post.
.RE
.sp
\f(CRautoload\fP
.RS 4
The autoload annotation allows you to autoload a zsh functions directory in addition to however the plugin was loaded as specified by \f(CRkind\fP. Supply a relative path to autoload (eg: \f(CRautoload:functions\fP).
.RE
.sp
\f(CRpin\fP
.RS 4
The pin annotation allows you to lock a bundle to a specific commit SHA. A full 40\-character SHA is required; a short SHA is an error. A pinned bundle will be cloned at the specified commit and will be skipped during \f(CRantidote update\fP. This is useful for preventing unwanted upstream changes from affecting your environment. Use \f(CRbranch:\fP for tags or branches.
.RE
.sp
Lines can also start with a directive. A directive occupies the first word of a line, is not a bundle itself, and affects the lines that follow it.
.sp
\f(CRusing:\fP
.RS 4
Lets you write plugins from a monorepo or a local directory as bare names (eg: \f(CRusing:ohmyzsh/ohmyzsh path:plugins\fP). Annotations you put on the directive carry over to those names, and anything a name sets for itself wins. Only one \f(CRusing:\fP is active at a time, so a new one replaces the last.
.RE
.sp
\f(CRpreset:\fP
.RS 4
Sets annotations that every later use of a bundle falls back on (eg: \f(CRpreset:ohmyzsh/ohmyzsh pin:<sha>\fP). It isn\(cqt a bundle itself, so nothing gets cloned.
.RE
.sp
.if n .RS 4
.nf
.fam C
using:ohmyzsh/ohmyzsh path:plugins
git
magic\-enter
.fam
.fi
.if n .RE
.sp
With a repo, \f(CRusing:\fP also clones it, and \f(CRpath:\fP becomes the prefix each bare name hangs off. Point it at a local directory instead and the names are resolved under that directory:
.sp
.if n .RS 4
.nf
.fam C
using:$ZDOTDIR/plugins
myplugin
.fam
.fi
.if n .RE
.sp
A repo only gets cloned once, which means \f(CRpin:\fP and \f(CRbranch:\fP have to agree everywhere you use it. Miss one and antidote tells you the pin or branch is inconsistent. Rather than repeat yourself on every line, set it once:
.sp
.if n .RS 4
.nf
.fam C
preset:ohmyzsh/ohmyzsh pin:4f8a1c2b9e7d3a6f5c0b8e2d7a9f4c1b6e3d8a52

ohmyzsh/ohmyzsh path:lib
ohmyzsh/ohmyzsh path:plugins/git
.fam
.fi
.if n .RE
.sp
You can preset any annotation, not just \f(CRpin:\fP and \f(CRbranch:\fP. Presets are the last place antidote looks, so anything on the line itself wins, and so does anything picked up from a \f(CRusing:\fP. Watch \f(CRpath:\fP though: on a \f(CRpreset:\fP line it is simply a default path, while on a \f(CRusing:\fP line it is a prefix for bare names.
.sp
Presets are matched on the directory a bundle clones into, so it makes no difference how you spell the repo. They reach bare names under a \f(CRusing:\fP too:
.sp
.if n .RS 4
.nf
.fam C
preset:ohmyzsh/ohmyzsh pin:4f8a1c2b9e7d3a6f5c0b8e2d7a9f4c1b6e3d8a52

using:ohmyzsh/ohmyzsh path:plugins
git
magic\-enter
.fam
.fi
.if n .RE
.sp
A preset only affects the lines below it. Set one twice for the same bundle and the second replaces the first, but presets for different bundles stack up rather than replacing each other the way \f(CRusing:\fP does.
.sp
Bundles can be kept a fixed number of days behind their upstream with the following \f(CRzstyle\fP:
.sp
.if n .RS 4
.nf
.fam C
zstyle \*(Aq:antidote:bundle:*\*(Aq min\-age 7
zstyle \*(Aq:antidote:bundle:foo/bar\*(Aq min\-age 30
zstyle \*(Aq:antidote:bundle:foo/baz\*(Aq min\-age 0\&    # always take the latest commit
.fam
.fi
.if n .RE
.sp
The default is unset, which is the same as \f(CR0\fP: no delay. Use \f(CR0\fP to opt a single bundle out of a \f(CRmin\-age\fP set for every bundle by pattern. With \f(CRmin\-age\fP set, cloning and updating stop at the newest commit that has been upstream at least that many days, which gives a bad push time to be noticed and pulled before it reaches your shell. Clones are unshallowed up front so the dated history is available, rather than in the background as antidote normally does, which makes the clone itself slower. Pinned bundles ignore \f(CRmin\-age\fP, since a pin already fixes the commit.
.sp
A brand new plugin has no commit old enough to satisfy \f(CRmin\-age\fP. Rather than refuse to install it, antidote clones the plugin at its latest commit and prints a note saying so. An update in that situation is skipped instead, leaving the bundle where it is. Either way, \f(CRmin\-age\fP never blocks you from getting a plugin.
.sp
Age is measured by commit date, and commit dates are set by whoever makes the commit, not by the host that receives the push. Anyone able to push a malicious commit can also date it far enough in the past to satisfy any \f(CRmin\-age\fP. Treat \f(CRmin\-age\fP as a cushion against a mistake or an unnoticed compromise, not as a supply chain guarantee. When you need a guarantee, use \f(CRpin:\fP, which fixes the commit SHA and makes no claim about dates.
.sp
Bundles are cloned shallow, at a single commit, so the first run is fast, then deepened by a background fetch. Nothing waits on that fetch. To hold a bundle at its shallow clone and skip it:
.sp
.if n .RS 4
.nf
.fam C
zstyle \*(Aq:antidote:bundle:*\*(Aq shallow yes\&                       # every bundle
zstyle \*(Aq:antidote:bundle:foo/bar\*(Aq shallow yes\&                 # just one
.fam
.fi
.if n .RE
.sp
The default is \f(CRno\fP. Pinned bundles are always left shallow, since a pin already fixes the commit. Loading, updating, pinning, and restoring a snapshot all work on a shallow bundle, and so does the commit list in the \f(CRantidote update\fP report. \f(CRantidote update\fP deepens any bundle it finds shallow unless that bundle is held shallow here, since the background fetch is best effort. Setting \f(CRmin\-age\fP on a bundle overrides holding it shallow: finding a commit old enough means searching history, which needs the full clone.
.sp
Cloned repo directory naming can be controlled with the following \f(CRzstyle\fP:
.sp
.if n .RS 4
.nf
.fam C
zstyle \*(Aq:antidote:bundle\*(Aq path\-style full\&     # github.com/owner/repo (default)
zstyle \*(Aq:antidote:bundle\*(Aq path\-style short\&    # owner/repo
zstyle \*(Aq:antidote:bundle\*(Aq path\-style escaped\&  # https\-COLON\-\-SLASH\-\-SLASH\-github.com\-SLASH\-owner\-SLASH\-repo
.fam
.fi
.if n .RE
.SH "OPTIONS"
.sp
\fB\-h, \-\-help\fP
.RS 4
Show the help documentation.
.RE
.sp
\fB<bundles>.\|.\|.\fP
.RS 4
Zsh plugin bundles.
.RE
.SH "EXAMPLES"
.sp
Using the \fBkind:\fP annotation:
.sp
.if n .RS 4
.nf
.fam C
# a regular plugin (kind:zsh is implied, so it\*(Aqs unnecessary)
antidote bundle zsh\-users/zsh\-history\-substring\-search kind:zsh
.fam
.fi
.if n .RE
.sp
.if n .RS 4
.nf
.fam C
# add prompt plugins to $fpath
antidote bundle sindresorhus/pure kind:fpath
.fam
.fi
.if n .RE
.sp
.if n .RS 4
.nf
.fam C
# add utility plugins to $PATH
antidote bundle romkatv/zsh\-bench kind:path
.fam
.fi
.if n .RE
.sp
.if n .RS 4
.nf
.fam C
# clone a repo for use in other ways
antidote bundle mbadolato/iTerm2\-Color\-Schemes kind:clone
.fam
.fi
.if n .RE
.sp
.if n .RS 4
.nf
.fam C
# autoload a functions directory
antidote bundle sorin\-ionescu/prezto path:modules/utility/functions kind:autoload
.fam
.fi
.if n .RE
.sp
.if n .RS 4
.nf
.fam C
# defer a plugin to speed up load times
antidote bundle olets/zsh\-abbr kind:defer
.fam
.fi
.if n .RE
.sp
Using the \fBbranch:\fP annotation:
.sp
.if n .RS 4
.nf
.fam C
# don\*(Aqt use the main branch, use develop instead
antidote bundle zsh\-users/zsh\-autosuggestions branch:develop
.fam
.fi
.if n .RE
.sp
Using the \fBpath:\fP annotation:
.sp
.if n .RS 4
.nf
.fam C
# load oh\-my\-zsh
antidote bundle ohmyzsh/ohmyzsh path:lib
antidote bundle ohmyzsh/ohmyzsh path:plugins/git
.fam
.fi
.if n .RE
.sp
Using the \fBpin:\fP annotation:
.sp
.if n .RS 4
.nf
.fam C
# pin a plugin to a specific commit SHA
antidote bundle zsh\-users/zsh\-autosuggestions pin:4f8a1c2b9e7d3a6f5c0b8e2d7a9f4c1b6e3d8a52
.fam
.fi
.if n .RE
.sp
.if n .RS 4
.nf
.fam C
# pin a plugin to a specific commit SHA
antidote bundle zsh\-users/zsh\-syntax\-highlighting pin:4f8a1c2b9e7d3a6f5c0b8e2d7a9f4c1b6e3d8a52
.fam
.fi
.if n .RE
.sp
Using the \fBconditional:\fP annotation:
.sp
.if n .RS 4
.nf
.fam C
# define a conditional function prior to loading antidote
function is_macos {
  [[ $OSTYPE == darwin* ]] || return 1
}

# conditionally load a plugin using the function you made
antidote bundle ohmyzsh/ohmyzsh path:plugins/macos conditional:is_macos
.fam
.fi
.if n .RE
.SH "BUGS"
.sp
See GitHub Issues: \c
.URL "https://github.com/mattmc3/antidote/issues" "" ""
.SH "AUTHORS"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Copyright (c) 2021\-2026 Matt McElheny
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
antidote contributors: \c
.URL "https://github.com/mattmc3/antidote/graphs/contributors" "" ""
.RE
.SH "LICENSE"
.sp
MIT