'\" t
.\"     Title: antidote-install
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.26
.\"      Date: 2025-12-12
.\"    Manual: Antidote Manual
.\"    Source: antidote
.\"  Language: English
.\"
.TH "ANTIDOTE\-INSTALL" "1" "2025-12-12" "antidote" "Antidote Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
antidote-install \- install a bundle
.SH "SYNOPSIS"
.sp
\fBantidote install\fP [\-h|\-\-help] [\-k|\-\-kind <kind>] [\-p|\-\-path <path>] [\-a|\-\-autoload <path>] [\-c|\-\-conditional <func>] [\-\-pre <func>] [\-\-post <func>] [\-b|\-\-branch <branch>] <bundle> [<bundlefile>]
.SH "DESCRIPTION"
.sp
\fBantidote\-install\fP clones a new bundle and adds it to your plugins file.
.sp
The default bundle file is \f(CR${ZDOTDIR:\-$HOME}/.zsh_plugins.txt\fP. This can be overridden with the following \f(CRzstyle\fP:
.sp
.if n .RS 4
.nf
.fam C
zstyle \*(Aq:antidote:bundle\*(Aq file /path/to/my/bundle_file.txt
.fam
.fi
.if n .RE
.SH "OPTIONS"
.sp
\fB\-h, \-\-help\fP
.RS 4
Show the help documentation.
.RE
.sp
\fB\-k, \-\-kind <kind>\fP
.RS 4
The kind of bundle. Valid values: autoload, fpath, path, clone, defer, zsh.
.RE
.sp
\fB\-p, \-\-path <path>\fP
.RS 4
A relative subpath within the bundle where the plugin is located.
.RE
.sp
\fB\-b, \-\-branch <branch>\fP
.RS 4
The git branch to use.
.RE
.sp
\fB\-a, \-\-autoload <path>\fP
.RS 4
A relative subpath within the bundle where autoload function files are located.
.RE
.sp
\fB\-c, \-\-conditional <func>\fP
.RS 4
A conditional function used to check whether to load the bundle.
.RE
.sp
\fB\-\-pre <func>\fP
.RS 4
A function to be called prior to loading the bundle.
.RE
.sp
\fB\-\-post <func>\fP
.RS 4
A function to be called after loading the bundle.
.RE
.sp
\fB<bundle>\fP
.RS 4
Bundle to be installed.
.RE
.sp
\fB[<bundlefile>]\fP
.RS 4
Bundle file to write to if not using the default. Defaults to \f(CR${ZDOTDIR:\-$HOME}/.zsh_plugins.txt\fP or the \f(CRzstyle\fP setting.
.RE
.SH "EXAMPLES"
.sp
.if n .RS 4
.nf
.fam C
antidote install zsh\-users/zsh\-history\-substring\-search
.fam
.fi
.if n .RE
.SH "BUGS"
.sp
See GitHub Issues: \c
.URL "https://github.com/mattmc3/antidote/issues" "" ""
.SH "AUTHORS"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Copyright (c) 2021\-2026 Matt McElheny
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
antidote contributors: \c
.URL "https://github.com/mattmc3/antidote/graphs/contributors" "" ""
.RE
.SH "LICENSE"
.sp
MIT