'\" t
.\"     Title: antidote-help
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.26
.\"      Date: 2025-12-12
.\"    Manual: Antidote Manual
.\"    Source: antidote
.\"  Language: English
.\"
.TH "ANTIDOTE\-HELP" "1" "2025-12-12" "antidote" "Antidote Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
antidote-help \- show antidote documentation
.SH "SYNOPSIS"
.sp
\fBantidote help\fP [<command>]
.SH "DESCRIPTION"
.sp
\fBantidote\-help\fP is used to show context\-sensitive help for antidote and its commands.
.SH "OPTIONS"
.sp
\fB\-h, \-\-help\fP
.RS 4
Inception\-style meta\-help recursively.
.RE
.sp
\fB<command>\fP
.RS 4
Show help for a specific command.
.RE
.SH "BUGS"
.sp
See GitHub Issues: \c
.URL "https://github.com/mattmc3/antidote/issues" "" ""
.SH "AUTHORS"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Copyright (c) 2021\-2026 Matt McElheny
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
antidote contributors: \c
.URL "https://github.com/mattmc3/antidote/graphs/contributors" "" ""
.RE
.SH "LICENSE"
.sp
MIT