#!/usr/bin/env zsh
0=${(%):-%x}
setopt extended_glob

cd ${0:A:h:h}

testfiles=()
if (( $# > 0 )); then
  testfiles=($@)
else
  testfiles=($PWD/tests/*.md~test_real*.md)
fi

# foo example test command
# env -i PATH=$PATH FPATH=$FPATH \
#  zsh -f -- =clitest --list-run --progress dot --prompt '%' --color always $PWD/tests/foo.md

env -i PATH=$PATH FPATH=$FPATH PAGER=cat \
    zsh -f -- \
    =clitest \
        --list-run --progress dot --prompt '%' \
        --color always \
        --pre-flight 'git --version; print $PWD $VENDOR $OSTYPE =zsh $ZSH_VERSION $ZSH_PATCHLEVEL' \
        -- $testfiles
