#!/usr/bin/env zsh
0=${(%):-%x}
setopt extended_glob

BASEDIR=${0:A:h:h}
TMPDIR=$BASEDIR/.tmp
TESTS_HOME=$BASEDIR/tests

# make sure our tests don't get hung up on git prompting
export GIT_TERMINAL_PROMPT=0

local o_unit
zparseopts -D -M -- -unit=o_unit || return 1

# make sure tests are executable
chmod 755 $TESTS_HOME/*test_*.zsh

export ZTAP_HOME=${ZTAP_HOME:-$TMPDIR/ztap}
if ! [[ -d $ZTAP_HOME ]]; then
  command git clone --depth 1 --quiet https://github.com/mattmc3/ztap $ZTAP_HOME
fi

source $ZTAP_HOME/ztap3.zsh
exitcode=0
if (( $# )); then
  ztap3 --color "$@"
elif (( $#o_unit )); then
  ztap3 --color $TESTS_HOME/test_*.zsh~*.real.zsh
else
  ztap3 --color $TESTS_HOME/test_*.zsh
fi
return $?
