#!/usr/bin/env zsh
0=${(%):-%x}
BASEDIR=${0:h:h}
cd $BASEDIR
print "loc:"
wc -l antidote.zsh ./functions/*(.)
print "sloc:"
for file in antidote.zsh ./functions/*(.); do
  lines=$(awk '/^ *[^#]+$/{print}' $file | wc -l)
  print $lines $file
done
print "sloc total:"
awk '/^ *[^#]+$/{print}' antidote.zsh ./functions/*(.) | wc -l
