#!/usr/bin/env zsh
0=${(%):-%x}
BASEDIR=${0:h:h}
cd $BASEDIR
echo "loc:"
wc -l antidote.zsh ./functions/*(.)
echo "sloc:"
for file in antidote.zsh ./functions/*(.); do
  lines=$(awk '/^ *[^#]+$/{print}' $file | wc -l)
  echo $lines $file
done
echo "sloc total:"
awk '/^ *[^#]+$/{print}' antidote.zsh ./functions/*(.) | wc -l
