# taken from: https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/.github/workflows/test.yml
# and adapted 

name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - master
      container:
        image: ghcr.io/zsh-users/zsh:${{ matrix.version }}
      steps:
        - uses: actions/checkout@v2

        - name: Test
          shell: zsh
          run: ./test/runtests | tail -1 | grep 'ok'

